### ISSUE TITLE
cannot install latest precommit-hook

### ISSUE THREAD

**Issue by mboughaba** [nlf/precommit-hook#59]
```shell
$ npm install precommit-hook
/
> git-validate@2.0.0 install /prj1/node_modules/precommit-hook/node_modules/git-validate
> node bin/install

|
> precommit-hook@3.0.0 install /prj1/node_modules/precommit-hook
> node bin/install

/prj1/node_modules/precommit-hook/bin/install:7
Validate.installScript('lint', 'jshint .');
         ^
TypeError: undefined is not a function
    at Object.<anonymous> (/prj1/node_modules/precommit-hook/bin/install:7:10)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

```shell

2.0.1 works just fine.
I assume this is trying to run a validation script before installing the dependency.

**Comment by nlf** [comment]
Had a mistake in git-validate, try reinstalling now

**Comment by mboughaba** [comment]
It is woking as expected now.
Thank you very much.
