### ISSUE TITLE
Can't install without a hooks directory

### ISSUE THREAD

**Issue by frapontillo** [nlf/precommit-hook#61]
After cloning my repo with Sourcetree (Mac OS X) the hooks directory didn't exist, therefore the installation failed.

```shell
Batmans-MBP:myproject fra$ npm install precommit-hook
|
> git-validate@2.0.2 install /Users/fra/Workspace/myproject/node_modules/precommit-hook/node_modules/git-validate
> node bin/install

fs.js:500
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT, no such file or directory '/Users/fra/Workspace/myproject/.git/hooks/pre-commit'
    at Error (native)
    at Object.fs.openSync (fs.js:500:18)
    at Object.fs.writeFileSync (fs.js:1099:15)
    at Object.exports.installHooks (/Users/fra/Workspace/myproject/node_modules/precommit-hook/node_modules/git-validate/lib/utils.js:240:12)
    at Object.<anonymous> (/Users/fra/Workspace/myproject/node_modules/precommit-hook/node_modules/git-validate/bin/install.js:3:7)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "precommit-hook"
npm ERR! node v0.12.5
npm ERR! npm  v2.11.2
npm ERR! code ELIFECYCLE

npm ERR! git-validate@2.0.2 install: `node bin/install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the git-validate@2.0.2 install script 'node bin/install'.
npm ERR! This is most likely a problem with the git-validate package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node bin/install
npm ERR! You can get their info via:
npm ERR!     npm owner ls git-validate
npm ERR! There is likely additional logging output above.
```

I have solved the issue by manually creating the directory and re-running the install process, but can this issue be solved on the module side?

Thanks!

**Comment by nlf** [comment]
sure can, see nlf/git-validate#29 which once merged will take care of this issue

**Comment by frapontillo** [comment]
Wow that was fast. Thanks! :+1:

**Comment by frapontillo** [comment]
Fix confirmed!
